Repository gnar-rengar/frontend, pull requests merged in 2022-06, with the labels that each got.

#7 [프로젝트 세팅] 디자인시스템 반영
  package-lock.json
  package.json
  src/pages/_app.tsx
  src/theme/globalStyle.tsx
  src/theme/index.ts
  src/types/emotion.d.ts
Labels: setting

#9 [버그] msw api 호출 문제
  .eslintrc.js
  src/mocks/handlers/index.ts
  src/mocks/index.ts
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: bug

#11 [공통 컴포넌트] 공통 레이아웃
  .eslintrc.js
  jest.config.js
  package-lock.json
  package.json
  src/__tests__/App.test.jsx
  src/__tests__/Header.test.tsx
  src/components/icons/ArrowLeft.tsx
  src/components/icons/Bell.tsx
  src/components/icons/BellRing.tsx
  src/components/icons/BookMark.tsx
  src/components/icons/Chat.tsx
  src/components/icons/ChevronDown.tsx
  src/components/icons/ChevronLeft.tsx
  src/components/icons/ChevronRight.tsx
  src/components/icons/CrossMark.tsx
  src/components/icons/Hamburger.tsx
  src/components/icons/Love.tsx
  src/components/icons/Profile.tsx
  src/components/icons/Search.tsx
  src/components/icons/Share.tsx
  src/components/icons/index.ts
  src/components/layout/Layout.style.tsx
  src/components/layout/Layout.tsx
  src/components/layout/header/Header.style.tsx
  src/components/layout/header/Header.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/theme/index.ts
  src/types/emotion.d.ts
Labels: feature

#16 [공통 컴포넌트] 공통 컴포넌트
  .eslintrc.js
  src/__tests__/App.test.jsx
  src/components/common/CheckBox.style.tsx
  src/components/common/CheckBox.tsx
  src/components/common/Chip.style.tsx
  src/components/common/Chip.tsx
  src/components/common/TextField.style.tsx
  src/components/common/TextField.tsx
  src/components/common/Typography.style.tsx
  src/components/common/Typography.tsx
  src/components/icons/BellRing.tsx
  src/components/icons/BookMark.tsx
  src/components/icons/ChevronDown.tsx
  src/components/icons/ChevronLeft.tsx
  src/components/icons/ChevronRight.tsx
  src/components/icons/CrossMark.tsx
  src/components/icons/Hamburger.tsx
  src/components/icons/Love.tsx
  src/components/icons/Share.tsx
  src/pages/_app.tsx
  src/theme/index.ts
  src/types/emotion.d.ts
  tsconfig.json
  tsconfig.test.json
Labels: feature

#21 [공통 컴포넌트] 체크 박스, 버튼 추가
  src/components/common/Button.style.tsx
  src/components/common/Button.tsx
  src/components/common/CheckBox.style.tsx
  src/components/common/CheckBox.tsx
  src/components/common/Chip.style.tsx
  src/components/common/TextField.style.tsx
  src/components/common/Typography.style.tsx
  src/components/common/Typography.tsx
  src/components/layout/Layout.style.tsx
  src/components/layout/header/Header.style.tsx
  src/theme/index.ts
  src/types/color.type.ts
  src/types/emotion.d.ts
  src/types/typography.type.ts
Labels: feature

#22 [온보딩] 온보딩 페이지 마크업
  src/__tests__/OnBoarding.test.tsx
  src/components/common/CheckBox.tsx
  src/components/common/Chip.style.tsx
  src/components/common/Chip.tsx
  src/components/common/TextField.style.tsx
  src/components/common/Typography.style.tsx
  src/components/common/Typography.tsx
  src/components/onBoarding/index.tsx
  src/components/onBoarding/style.ts
  src/constant/index.ts
  src/pages/on-boarding.tsx
  src/theme/index.ts
  src/types/emotion.d.ts
Labels: feature, markup

#27 UDFM-24 - 프론트엔드 마이 페이지
  src/components/common/asking/Asking.style.tsx
  src/components/common/asking/Asking.tsx
  src/components/common/basic-container/BasicContainer.tsx
  src/components/common/button/Button.style.tsx
  src/components/common/button/Button.tsx
  src/components/common/card/Card.style.tsx
  src/components/common/card/Card.tsx
  src/components/common/checkbox/CheckBox.style.tsx
  src/components/common/checkbox/CheckBox.tsx
  src/components/common/chip/Chip.style.tsx
  src/components/common/chip/Chip.tsx
  src/components/common/divider/Divider.style.tsx
  src/components/common/divider/Divider.tsx
  src/components/common/index.ts
  src/components/common/radio/Radio.style.tsx
  src/components/common/radio/Radio.tsx
  src/components/common/textfield/TextField.style.tsx
  src/components/common/textfield/TextField.tsx
  src/components/common/typography/Typography.style.tsx
  src/components/common/typography/Typography.tsx
  src/components/mypage/FeedBack.tsx
  src/components/mypage/index.tsx
  src/components/mypage/style.tsx
  src/components/onBoarding/index.tsx
  src/components/reviewWrite/index.tsx
  src/pages/mypage.tsx
Labels: markup

#30 onboarding mocking
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/components/common/radio/Radio.tsx
  src/components/onBoarding/index.tsx
  src/components/onBoarding/style.ts
  src/constant/index.ts
  src/hooks/useOnBoardingMutation.tsx
  src/mocks/handlers/index.ts
  src/types/onBoarding.type.ts
Labels: feature

#37 Udfm 36 카카오 로그인 구현
  next.config.js
  src/components/common/button/Button.tsx
  src/components/login/index.tsx
  src/components/login/style.ts
  src/hooks/useLogin.ts
  src/hooks/useOnBoardingMutation.ts
  src/pages/_app.tsx
  src/pages/login.tsx
  src/types/dto/login.type.ts
Labels: feature
