Repository gnar-rengar/frontend, pull requests merged in 2022-08, with the labels that each got.

#81 [채팅] 비속어 필터
  next.config.js
  package-lock.json
  package.json
  src/components/chatRoom/BadWordAlert.tsx
  src/components/chatRoom/Header.tsx
  src/components/chatRoom/InputArea.tsx
  src/components/chatRoom/MessageArea.tsx
  src/components/chatRoom/QuickChat.tsx
  src/components/chatRoom/index.tsx
  src/components/chatRoom/style.tsx
  src/hooks/queryKeys.ts
  src/hooks/useGetMessages.tsx
  src/hooks/useGetOpponent.tsx
  src/hooks/useGetRoomId.ts
  src/pages/_app.tsx
  src/types/testfile.d.ts
  src/utils/filters.txt
  src/utils/index.ts
Labels: feature, markup

#86 Udfm 88 성향 검사 공유하기
  public/icons/link.svg
  public/icons/save.svg
  src/components/common/chip/CheckBoxChip.tsx
  src/components/home/index.tsx
  src/components/home/style.ts
  src/components/layout/header/Header.style.tsx
  src/components/onBoarding/index.tsx
  src/components/recommend/New.tsx
  src/components/tendencyTest/End.tsx
  src/components/tendencyTest/style.ts
  src/hooks/useGetAuth.ts
  src/hooks/useGetNewSummonerList.ts
  src/hooks/useGetOnBoarding.ts
  src/pages/_document.tsx
  src/theme/index.ts
  src/types/api.type.ts
  src/types/kakao.type.ts
  src/types/theme.type.ts
Labels: feature, markup

#88 [QA] 카드 플레이스타일 수정
  src/components/chats/index.tsx
  src/components/common/card/ImageArea.tsx
  src/components/common/card/InfoArea.tsx
  src/components/common/card/LargeCard.tsx
  src/components/common/card/PlayStyle.tsx
  src/components/common/card/style.tsx
  src/components/layout/Layout.style.tsx
  src/components/myPage/index.tsx
  src/components/myPage/style.tsx
  src/components/profile/ButtonArea.tsx
  src/components/profile/PlayStyleSection.tsx
  src/components/profile/QueueInfo.tsx
  src/components/profile/ReviewSection.tsx
  src/components/profile/index.tsx
  src/pages/my-page.tsx
  tsconfig.json
Labels: feature, markup

#93 Udfm 92 채팅 작성 중
  .github/workflows/deploy.yml
  src/components/chatRoom/InputArea.tsx
  src/components/chatRoom/MessageArea.tsx
  src/components/chatRoom/Typing.tsx
  src/components/chatRoom/index.tsx
  src/components/chatRoom/style.tsx
  src/components/layout/Layout.style.tsx
  src/components/layout/header/Header.tsx
  src/hooks/queryKeys.ts
  src/hooks/useGetMessages.tsx
Labels: bug, enhancement

#94 Udfm 93 new list custom list 수정
  public/icons/checkCircle.svg
  src/components/chatRoom/index.tsx
  src/components/chats/index.tsx
  src/components/home/index.tsx
  src/components/myPage/index.tsx
  src/components/onBoarding/index.tsx
  src/components/profile/index.tsx
  src/components/recommend/Fit.tsx
  src/components/recommend/New.tsx
  src/components/withdrawal/Success.tsx
  src/components/withdrawal/Withdrawal.tsx
  src/components/withdrawal/style.ts
  src/hooks/queryKeys.ts
  src/hooks/useGetAuth.ts
  src/hooks/useGetFitSummonerList.ts
  src/hooks/useGetNewSummonerList.ts
  src/hooks/useWithdrawalMutation.ts
  src/pages/withdrawal/index.tsx
  src/pages/withdrawal/success.tsx
Labels: bug, enhancement, markup

#96 Udfm 96 필터링 결과 디자인
  public/icons/user.svg
  src/components/login/index.tsx
  src/components/recommend/Filter.tsx
  src/components/recommend/New.tsx
  src/components/recommend/None.tsx
  src/components/recommend/style.ts
Labels: markup

#97 Udfm 97 카카오톡 공유 마무리
  src/components/tendencyTest/End.tsx
Labels: enhancement, feature

#95 Udfm 95 온보딩 포지션 수정
  public/icons/cat.png
  src/components/common/chip/CheckBoxChip.tsx
  src/components/home/index.tsx
  src/components/login/index.tsx
  src/components/onBoarding/index.tsx
  src/components/onBoarding/style.ts
  src/components/tendencyTest/Question.tsx
  src/hooks/useGetAuth.ts
  src/hooks/useGetFitSummonerList.ts
  src/types/api.type.ts
Labels: bug, enhancement

#107 Udfm 89 프론트엔드 qa
  src/components/chatRoom/index.tsx
  src/components/chats/index.tsx
  src/components/myPage/index.tsx
  src/components/onBoarding/index.tsx
  src/components/profile/PlayStyleSection.tsx
  src/components/profile/index.tsx
  src/components/profile/style.ts
  src/components/recommend/Fit.tsx
  src/hooks/preFetchFns.ts
  src/hooks/useGetAuth.ts
  src/hooks/useGetMessages.tsx
  src/hooks/useGetMyPage.ts
  src/hooks/useGetOnBoarding.ts
  src/hooks/useLogoutMutation.ts
  src/hooks/useMessages.ts
  src/pages/chats/[roomId].tsx
  src/pages/chats/index.tsx
  src/pages/index.tsx
  src/pages/my-page.tsx
  src/pages/on-boarding.tsx
  src/pages/profile/[userId].tsx
  src/pages/recommend/fit.tsx
  src/types/api.type.ts
Labels: enhancement

#108 Udfm 105 오픈그래프 추가
  next.config.js
  src/components/tendencyTest/End.tsx
  src/constant/index.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/tendency-test.tsx
Labels: feature

#114 Udfm 107 성향검사 플로우 수정
  src/components/WithAuth.tsx
  src/components/login/index.tsx
  src/components/onBoarding/index.tsx
  src/components/tendencyTest/End.tsx
  src/hooks/useGetAuth.ts
  src/hooks/useLogin.ts
  src/pages/_document.tsx
Labels: enhancement

#119 Udfm 109 홈 블러 수정
  src/components/home/Blur.tsx
  src/components/home/index.tsx
  src/hooks/useLogin.ts
  src/pages/tendency-test.tsx
  src/types/api.type.ts
Labels: enhancement

#122 Udfm 110 온보딩 성향검사 플로우 수정
  .eslintrc.js
  src/atom/index.ts
  src/components/WithAuth.tsx
  src/components/onBoarding/ChoicePlayStyle.tsx
  src/components/onBoarding/PlayStyleChip.tsx
  src/components/onBoarding/index.tsx
  src/components/onBoarding/style.ts
  src/components/tendencyTest/End.tsx
  src/components/tendencyTest/Start.tsx
  src/components/tendencyTest/style.ts
  src/constant/index.ts
  src/hooks/useLogin.ts
  src/hooks/useLogoutMutation.ts
  src/hooks/useOnBoardingMutation.ts
  src/pages/_app.tsx
  src/pages/on-boarding.tsx
  src/pages/tendency-test.tsx
  src/types/api.type.ts
Labels: enhancement, feature
