Repository gnar-rengar/frontend, pull requests merged in 2022-07, with the labels that each got.

#38 [마이 페이지] 카드 컴포넌트 추가
  .gitignore
  src/__tests__/MyPage.test.tsx
  src/axios/index.ts
  src/components/common/card/Card.style.tsx
  src/components/common/card/Card.tsx
  src/components/common/card/MostChamp.tsx
  src/components/common/card/PlayStyle.tsx
  src/components/common/card/Position.tsx
  src/components/common/card/Profile.tsx
  src/components/common/card/Tier.tsx
  src/components/common/card/style.tsx
  src/components/common/chip/Chip.style.tsx
  src/components/common/chip/Chip.tsx
  src/components/common/chip/SelectChip.tsx
  src/components/common/radio/Radio.style.tsx
  src/components/myPage/index.tsx
  src/components/myPage/style.tsx
  src/components/onBoarding/index.tsx
  src/hooks/useGetMyPage.ts
  src/hooks/useOnBoardingMutation.tsx
Labels: feature

#41 Udfm 35 프론트엔드 로그인 페이지
  next.config.js
  package-lock.json
  package.json
  src/axios/index.ts
  src/axios/tokenRefresh.ts
  src/components/common/button/Button.tsx
  src/components/login/index.tsx
  src/components/login/style.ts
  src/hooks/useLogin.ts
  src/hooks/useOnBoardingMutation.ts
  src/pages/_app.tsx
  src/pages/login.tsx
  src/types/api.type.ts
Labels: feature

#47 Udfm 57 온보딩 UI 수정 사항 변경 및 성향 검사 페이지 마크업
  public/expression/cemetery.png
  public/expression/conflict.png
  public/expression/cookie.png
  public/expression/cupcake.png
  public/expression/penguin.png
  public/expression/zed.png
  public/icons/onBoarding.png
  src/components/common/asking/Asking.tsx
  src/components/common/button/Button.style.tsx
  src/components/common/button/Button.tsx
  src/components/common/chip/CheckBoxChip.tsx
  src/components/common/chip/Chip.style.tsx
  src/components/common/chip/Chip.tsx
  src/components/common/chip/RadioChip.tsx
  src/components/common/textfield/TextField.style.tsx
  src/components/common/textfield/TextField.tsx
  src/components/common/typography/Typography.style.tsx
  src/components/common/typography/Typography.tsx
  src/components/layout/Layout.tsx
  src/components/onBoarding/index.tsx
  src/components/onBoarding/style.ts
  src/components/tendencyTest/End.tsx
  src/components/tendencyTest/Question.tsx
  src/components/tendencyTest/Start.tsx
  src/components/tendencyTest/index.tsx
  src/components/tendencyTest/style.ts
  src/constant/index.ts
  src/hooks/useOnBoardingMutation.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/user.ts
  src/pages/_app.tsx
  src/pages/tendency-test.tsx
  src/types/api.type.ts
Labels: feature, markup

#52 UDFM-66-마크업
  public/icons/discord.svg
  public/icons/kakao.svg
  public/icons/main-logo.svg
  public/icons/naver.svg
  src/components/common/typography/Typography.style.tsx
  src/components/common/typography/Typography.tsx
  src/components/login/index.tsx
  src/components/login/style.ts
  src/pages/login.tsx
  src/theme/index.ts
  src/types/theme.type.ts
Labels: markup

#54 Udfm 69 마트업
  package-lock.json
  package.json
  public/banner/home.png
  public/icons/arrow-right.svg
  src/components/common/card/InfoArea.tsx
  src/components/common/card/LargeCard.tsx
  src/components/common/card/PlayStyle.tsx
  src/components/common/card/SmallCard.tsx
  src/components/common/card/style.tsx
  src/components/common/chip/Chip.style.tsx
  src/components/common/footer/Footer.style.tsx
  src/components/common/footer/Footer.tsx
  src/components/common/index.ts
  src/components/home/BannerSwiper.tsx
  src/components/home/RecommendSwiper.tsx
  src/components/home/index.tsx
  src/components/home/style.ts
  src/components/onBoarding/index.tsx
  src/pages/index.tsx
  src/theme/index.ts
Labels: markup

#60 Udfm 75 마크업
  public/expression/cry.png
  src/components/common/checkbox/CheckBox.tsx
  src/components/common/textarea/index.tsx
  src/components/onBoarding/index.tsx
  src/components/withdrawal/index.tsx
  src/components/withdrawal/style.ts
  src/constant/index.ts
  src/hooks/useOnBoardingMutation.ts
  src/hooks/useWithdrawalMutation.ts
  src/pages/withdrawal.tsx
  src/types/api.type.ts
Labels: feature, markup

#61 Udfm 65 온보딩 api 백엔드 테스트
  src/components/common/chip/CheckBoxChip.tsx
  src/components/common/chip/RadioChip.tsx
  src/components/common/textfield/TextField.style.tsx
  src/components/myPage/index.tsx
  src/components/onBoarding/index.tsx
  src/components/onBoarding/style.ts
  src/constant/index.ts
  src/hooks/queryKeys.ts
  src/hooks/useGetMatchHistory.ts
  src/hooks/useGetMyPage.ts
  src/hooks/useGetOnBoarding.ts
  src/hooks/useGetUserProfile.ts
  src/hooks/useOnBoardingMutation.ts
  src/pages/on-boarding.tsx
  src/types/api.type.ts
Labels: feature, markup

#67 Udfm 79 성향검사 알고리즘 작업
  .eslintrc.js
  src/components/common/chip/Chip.style.tsx
  src/components/common/chip/Chip.tsx
  src/components/common/chip/RadioChip.tsx
  src/components/onBoarding/index.tsx
  src/components/tendencyTest/End.tsx
  src/components/tendencyTest/Question.tsx
  src/components/tendencyTest/Start.tsx
  src/components/tendencyTest/index.tsx
  src/components/tendencyTest/style.ts
  src/constant/index.ts
  src/hooks/useGetUserProfile.ts
Labels: feature

#70 Udfm 81 쿠키 설정 테스트
  src/hooks/queryKeys.ts
  src/hooks/useGetAuth.ts
  src/hooks/useLogin.ts
  src/hooks/useLogoutMutation.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/types/api.type.ts
  src/utils/index.ts
Labels: feature

#71 Udfm 35 프론트엔드 로그인 페이지
  public/icons/discord.svg
  public/icons/kakao.svg
  public/icons/main-logo.svg
  public/icons/naver.svg
  src/__tests__/App.test.jsx
  src/components/common/typography/Typography.tsx
  src/components/login/index.tsx
  src/components/login/style.ts
  src/components/tendencyTest/Question.tsx
  src/components/userProfile/index.tsx
  src/hooks/queryKeys.ts
  src/hooks/useGetAuth.ts
  src/hooks/useLogin.ts
  src/hooks/useLogoutMutation.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/theme/index.ts
  src/types/api.type.ts
  src/types/theme.type.ts
  src/utils/index.ts
Labels: feature, markup

#75 Udfm 84 로그아웃
  src/axios/index.ts
  src/axios/tokenRefresh.ts
  src/components/login/index.tsx
  src/components/myPage/index.tsx
  src/components/onBoarding/index.tsx
Labels: feature
